version: '3.9'
services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www
    platform: linux/amd64
    ports:
      - ${WEB_PORT}:80



  db:
    image: mysql:latest
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    # 80番ポートを割り当て
    ports:
      - ${DB_PORT}:3306
